# NumPy 和陣列導向的程式設計

`NumPy` 可以說是 Python 中最最標準的科學計算、數據分析套件。也因為 `NumPy` 的出現, 讓 Python 有了非常好的數據分析基礎, 一直到現在成為數據分析覇主。

In [5]:
import numpy as np

## 1. 陣列導向 101

科學計算一個很核心的概念叫 "array oriented" 的寫法。Array 是 `numpy` 標準的資料結構, 和 list 很像, 但就差了那麼一點點。而這一點點讓我們在計算上是無比的方便。

### 【暖身】 計算平均

某位同學期中考各科成績如下, 請幫他計算成績。

    grades = [77, 85, 56, 90, 66]
    
請計算平均。

In [4]:
s = 0
grades = [77, 85, 56, 90, 66]
for i in grades:
    s = s + i
print("average = {0:.2f}, sum = {1}".format(s/len(grades), s))

average = 74.80, sum = 374


### 【示範】陣列導向

In [10]:
grades = [77, 85, 56, 90, 66]
arr = np.array(grades)
arr.mean()

np.float64(74.8)

最大值

In [11]:
arr.max()

np.int64(90)

標準差

In [12]:
arr.std()

np.float64(12.416118556135006)

### 【暖身】 換算匯率

假設今天我想查查號稱 Pentax 三公主的 31mm, 43mm, 77mm 三隻 limited 鏡頭在美國賣多少。於是我去 B&H 查了他們的價格分別是:

    prices = [1096.95, 596.95, 896.95]
    
我又查了 Google 匯率 1 美金為 31.71 元。請把三支鏡頭的價格換算為台幣。

In [15]:
prices = [1096.95, 596.95, 896.95]
usdtotwd = 31.71
twd_prices = []
for i in prices:
    twd = i * usdtotwd 
    twd_prices.append(twd)
print("台幣價格：", twd_prices)

台幣價格： [34784.2845, 18929.2845, 28442.2845]


先不管這實在有夠醜的數字, 我們要記得在科學計算中:

### 儘可能不要使用迴圈

這可能嗎?

### 【示範】陣列換算匯率

In [17]:
prices = [1096.95, 596.95, 896.95]
prices = np.array(prices)
usdtotwd = 31.71
prices * usdtotwd

array([34784.2845, 18929.2845, 28442.2845])

哦哦, 傑克, 這太神奇了!

## 2. 其實 array 還有很多功能

### 【練習】 成績計算

一位老師成績這樣算的:

* 平時成績 20%
* 期中考   35%
* 期未考   45%

有位同學

* 平時成績 85 分
* 期中 70 分
* 期末 80 分

這位同學的學期成績是多少?

In [19]:
grades = np.array([85,70,80])
weights = np.array([0.2, 0.35, 0.45])

這還不是我們要的最終成績啊!

In [25]:
grades * weights

array([17. , 24.5, 36. ])

### 【提示】 array 還有很多函數可以用

可以先打入

    weighted_grades.
    
先不要按 `enter` 或 `shift-enter`, 而是按 `tab`...


In [26]:
weighted_grades = grades * weights
weighted_grades.sum()

np.float64(77.5)

### 【技巧】 一行完成成績計算

In [27]:
np.dot(grades, weights)

np.float64(77.5)

## 3. 重要的 array 大變身!

我們在數據分析, 常常要改 array 的型式。

### 【練習】 一個 50 個數字的 array

先想辦法、用亂數做出 50 個數字的 array, 叫做 A 好了。

In [28]:
A = np.random.rand(50)
A

array([0.44812679, 0.9613666 , 0.66997161, 0.8522901 , 0.5902578 ,
       0.17656219, 0.26361466, 0.6820874 , 0.78290202, 0.74572198,
       0.60590022, 0.95676347, 0.86654235, 0.42980791, 0.55472435,
       0.11892052, 0.07959616, 0.36193555, 0.68034046, 0.97299722,
       0.90996352, 0.9423405 , 0.30111179, 0.68689561, 0.11321858,
       0.53028322, 0.2313141 , 0.24406385, 0.59078796, 0.6602663 ,
       0.62714293, 0.46734672, 0.82780776, 0.74137167, 0.6364745 ,
       0.11208291, 0.93110418, 0.77215541, 0.28454302, 0.97606367,
       0.80879426, 0.5237697 , 0.20962211, 0.02050626, 0.8526736 ,
       0.08043292, 0.70020793, 0.03639569, 0.38091338, 0.58667574])

In [31]:
A[0]

np.float64(0.44812679242659326)

### 【技巧】 檢查 A 的 `shape`

In [30]:
A.shape

(50,)

### 【技巧】 更改 A 的 shape

In [37]:
A.shape = (5,10)
A[0,9]

np.float64(0.7457219824623448)

### 【技巧】 也可以用 `reshape`

但要注意, reshape 並沒有改原來的陣列。

In [39]:
A.reshape(10,5)

array([[0.44812679, 0.9613666 , 0.66997161, 0.8522901 , 0.5902578 ],
       [0.17656219, 0.26361466, 0.6820874 , 0.78290202, 0.74572198],
       [0.60590022, 0.95676347, 0.86654235, 0.42980791, 0.55472435],
       [0.11892052, 0.07959616, 0.36193555, 0.68034046, 0.97299722],
       [0.90996352, 0.9423405 , 0.30111179, 0.68689561, 0.11321858],
       [0.53028322, 0.2313141 , 0.24406385, 0.59078796, 0.6602663 ],
       [0.62714293, 0.46734672, 0.82780776, 0.74137167, 0.6364745 ],
       [0.11208291, 0.93110418, 0.77215541, 0.28454302, 0.97606367],
       [0.80879426, 0.5237697 , 0.20962211, 0.02050626, 0.8526736 ],
       [0.08043292, 0.70020793, 0.03639569, 0.38091338, 0.58667574]])

### 【技巧】 拉平 `ravel`

雖然你想一想就知道可以用 `shape` 或 `reshape` 把多維陣列拉成一維。不過用 `ravel` 很潮。

In [41]:
A.ravel()

array([0.44812679, 0.9613666 , 0.66997161, 0.8522901 , 0.5902578 ,
       0.17656219, 0.26361466, 0.6820874 , 0.78290202, 0.74572198,
       0.60590022, 0.95676347, 0.86654235, 0.42980791, 0.55472435,
       0.11892052, 0.07959616, 0.36193555, 0.68034046, 0.97299722,
       0.90996352, 0.9423405 , 0.30111179, 0.68689561, 0.11321858,
       0.53028322, 0.2313141 , 0.24406385, 0.59078796, 0.6602663 ,
       0.62714293, 0.46734672, 0.82780776, 0.74137167, 0.6364745 ,
       0.11208291, 0.93110418, 0.77215541, 0.28454302, 0.97606367,
       0.80879426, 0.5237697 , 0.20962211, 0.02050626, 0.8526736 ,
       0.08043292, 0.70020793, 0.03639569, 0.38091338, 0.58667574])

## 4. 快速 array 生成法

### 【技巧】 都是 0 的 array

In [45]:
np.zeros(10)
np.zeros([10,3])

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

### 【技巧】 都是 1 的 array

In [44]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

### 【技巧】單位矩陣

In [47]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

### 【技巧】給定範圍均勻生出 n 個點

In [50]:
x = np.linspace(1,6,100)
x

array([1.        , 1.05050505, 1.1010101 , 1.15151515, 1.2020202 ,
       1.25252525, 1.3030303 , 1.35353535, 1.4040404 , 1.45454545,
       1.50505051, 1.55555556, 1.60606061, 1.65656566, 1.70707071,
       1.75757576, 1.80808081, 1.85858586, 1.90909091, 1.95959596,
       2.01010101, 2.06060606, 2.11111111, 2.16161616, 2.21212121,
       2.26262626, 2.31313131, 2.36363636, 2.41414141, 2.46464646,
       2.51515152, 2.56565657, 2.61616162, 2.66666667, 2.71717172,
       2.76767677, 2.81818182, 2.86868687, 2.91919192, 2.96969697,
       3.02020202, 3.07070707, 3.12121212, 3.17171717, 3.22222222,
       3.27272727, 3.32323232, 3.37373737, 3.42424242, 3.47474747,
       3.52525253, 3.57575758, 3.62626263, 3.67676768, 3.72727273,
       3.77777778, 3.82828283, 3.87878788, 3.92929293, 3.97979798,
       4.03030303, 4.08080808, 4.13131313, 4.18181818, 4.23232323,
       4.28282828, 4.33333333, 4.38383838, 4.43434343, 4.48484848,
       4.53535354, 4.58585859, 4.63636364, 4.68686869, 4.73737

### 【技巧】`range` 的 array 版

就是 `arange`。

In [51]:
np.arange(1,20,0.5)

array([ 1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,  5.5,  6. ,
        6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. , 10.5, 11. , 11.5,
       12. , 12.5, 13. , 13.5, 14. , 14.5, 15. , 15.5, 16. , 16.5, 17. ,
       17.5, 18. , 18.5, 19. , 19.5])

## 5. 超重要 `axis` 觀念

初學 `numpy` 很多人有點弄不清楚 `axis` 概念。其實掌握矩陣, 或很像矩陣的陣列都是「先列後行」就可以!

我們先弄個 array 來練習。

In [56]:
A = np.arange(10).reshape(2,5)
A

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

### 【重點】 一列一列算下來是 `axis=0`

![axis=0](images/axis0.png)

In [58]:
A.sum(axis = 0)

array([ 5,  7,  9, 11, 13])

### 【重點】 一行一行算過去是 `axis=1`

![axis=1](images/axis1.png)

In [59]:
A.sum(axis = 1)

array([10, 35])

### 【提示】當然也有可能全部算

In [60]:
A.sum()

np.int64(45)

## 6. array 過濾器

篩出我們要的資料, 這樣的技巧非常重要!

### 【例子】篩出大於 0 的數

我們有個陣列, 想找出大於 0 的數。<br>
L = np.array([3, -2, -1, 5, 7, -3])

In [77]:
L = np.array([3, -2, -1, 5, 7, -3])

我們可以很白痴的自己判斷...<br>
c = np.array([True,False,False,True,True,False])

In [78]:
c = np.array([True,False,False,True,True,False])

這是做啥呢? 我們可以瞬間...

In [79]:
L[c]

array([3, 5, 7])

除了自己做很白痴, 這看來很厲害!

事實上我們可以叫 `numpy` 做!

In [80]:
L > 0

array([ True, False, False,  True,  True, False])

這有點強, 我們還可以一次到位!

In [81]:
L = L[L > 0]
L

array([3, 5, 7])

## 7. 次元切割刀

`numpy` 中 array 的切割法和 list 很像。

In [93]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [94]:
x[3:7]

array([3, 4, 5, 6])

### 【技巧】2維陣列切法

記得先列後行!

In [95]:
x.shape = (2,5)
x

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

要所有的row, 切出行 1-3 位置。

In [97]:
x[:,1:3]

array([[1, 2],
       [6, 7]])

要所有的行col, 切出第 1 列row!

In [100]:
x[1,:]

array([5, 6, 7, 8, 9])

## 8. `NumPy` 的 `zip` 和 `unzip`

之前我們介紹 list 可以用 `zip` 和 `unzip` (其實還是 `zip`) 做到的資料格式變換, 在 array 中怎麼做呢?

![zip and unzip](images/zip.png)

### 【重點】array 的 `zip`

![array zip](images/arrzip.png)

In [102]:
x = np.array([1,2,3,4])
y = np.array([5,6,7,8])

In [103]:
X = np.c_[x, y]
X

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [105]:
Y = np.r_[x, y]
Y

array([1, 2, 3, 4, 5, 6, 7, 8])

### 【重點】array 的 `unzip`

這裡其實只需要用到 array 的切割法...

![array zip](images/arrunzip.png)

In [106]:
X[:,0]

array([1, 2, 3, 4])

In [107]:
X[:,1]

array([5, 6, 7, 8])